version: "3"
services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    stdin_open: true
    tty: true

  redis:
    image: redis:6.2-alpine
    command: --port 6380
    ports:
      - 6380:6380
    volumes:
      - cache:/data
    networks:
      - backend

volumes:
  cache:
networks:
  backend:
